rango/urls.py
from django.urls import path
from rango import views
from django.conf import settings 
from django.conf.urls.static import static


app_name = 'rango'


urlpatterns = [ 
    path('', views.index, name='index'),
    path('about/', views.about, name="about"),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'), 
	path('add_category/', views.add_category, name='add_category'),
]

#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    #views.show_category, name='show_category'),

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
]

rango/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField()
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name) 
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

rango/views.py
from django.shortcuts import render
from rango.models import Category
from rango.models import Page
from django.http import HttpResponse
from rango.forms import CategoryForm 
from django.shortcuts import redirect

def add_category(request):
	form = CategoryForm()


	if request.method == 'POST':
		form = CategoryForm(request.POST)


		if form.is_valid():
			form.save(commit=True)  
			return redirect('/rango/') 
		else:
			print(form.errors) 
			

	return render(request, 'rango/add_category.html', {'form': form})


def index(request):
    
    
	category_list = Category.objects.order_by('-likes')[:5] 

	context_dict = {}
	context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
	context_dict['categories'] = category_list

	return render(request, 'rango/index.html', context=context_dict)
def show_category(request, category_name_slug):

    context_dict = {}

    try:

        category = Category.objects.get(slug=category_name_slug)

        pages = Page.objects.filter(category=category)


        context_dict['pages'] = pages

        context_dict['category'] = category

    except Category.DoesNotExist:

        context_dict['category'] = None
        context_dict['pages'] = None

    return render(request, 'rango/category.html', context=context_dict)

templates/rango/add_category.html
<!DOCTYPE html> 
<html>
	<head> 
		<title>Rango</title> 
	</head>
	<body>
		<h1>Add a Category</h1> 
		<div>
			<form id="category_form" method="post" action="/rango/add_category/">
				{% csrf_token %} 
				{% for hidden in form.hidden_fields %}
					{{ hidden }} 
				{% endfor %} 
				{% for field in form.visible_fields %}
					{{ field.errors }}
					{{ field.help_text }}
					{{ field }} 
				{% endfor %}
				<input type="submit" name="submit" value="Create Category"/>
			</form>
		</div>
	</body>
</html>

templates/rango/category.html
<!DOCTYPE html>

<html>

    <head> 
        <title>Rango</title> 
    </head>

    <body>
        <div> 
        {% if category %} 
            <h1>{{ category.name }}</h1> 
            {% if pages %} 
            <ul> 
                {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %} 
            </ul> 
            {% else %} 
            <strong>No pages currently in category.</strong> 
            {% endif %} 
        {% else %} 
            The specified category does not exist.
            {% endif %} 
        </div> 
    </body>

</html>

templates/rango/index.html
<!DOCTYPE html> 
{% load staticfiles %}
<html>	
	<head> <title>Rango</title> </head>

	<body>
		<h1>Rango says...</h1> 
		<div>
			hey there partner! <br />
			<strong>{{ boldmessage }}</strong><br /> 
			<a href="/rango/add_category/">Add a New Category</a><br />
		</div> 
		        <div> 
            {% if categories %}
                <ul>
                    {% for category in categories %} 
                    <li>{{ category.name }}</li>
                {% endfor %}
                </ul>
            {% else %}
                <strong>There are no categories present.</strong>     
            {% endif %}
        </div> 
        <ul>
            	{% for category in categories %} 
        <li>
    	<a href="/rango/category/{{ category.slug }}/">{{ category.name }}</a>
        </li>
            	{% endfor %}
        </ul>
		<div>
			<a href="/rango/about/">About</a><br />
			<a href="{% url 'rango:about' %}">About</a>
			<img src="{% static 'images//rango.jpg' %}" alt="Picture of Rango" />
		</div> 
	</body>

</html>